# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wordy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wordy
  pod 'React', :path => '../node_modules/react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'wordy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wordyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'wordy-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wordy-tvOS

  target 'wordy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
